# Generated by Django 4.2.16 on 2025-01-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dojo",
            name="place_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
