# Generated by Django 4.2.16 on 2025-01-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0002_alter_dojo_place_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dojo",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dojo",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
