# Generated by Django 4.2.16 on 2025-01-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0003_alter_dojo_latitude_alter_dojo_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dojo",
            name="hours",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
