# Generated by Django 4.2.16 on 2025-01-23 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0006_practiceday"),
    ]

    operations = [
        migrations.AddField(
            model_name="dojo",
            name="reviews",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="review",
            name="dojo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dojo_reviews",
                to="dojo.dojo",
            ),
        ),
    ]
