# Generated by Django 4.2.16 on 2025-01-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0007_dojo_reviews_alter_review_dojo"),
    ]

    operations = [
        migrations.AddField(
            model_name="dojo",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
