# Generated by Django 4.2.16 on 2025-01-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0008_dojo_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="dojo",
            name="user_ratings_total",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
